# basic settings, like url or pool size, are not here.
# just explicitly specify hikari, for example for Spring Boot 1.x
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# any HikariCP version, explicitly set value ...data-source-properties.loginTimeout * 1000
spring.datasource.hikari.connection-timeout=33000

# pgJDBC 9.1.901+
spring.datasource.hikari.data-source-properties.ApplicationName=appName

# pgJDBC 9.4.1200+, makes sense to specify starting from server version 9.0+
spring.datasource.hikari.data-source-properties.assumeMinServerVersion=10.0

# pgJDBC 9.3.1102+, choose the timeout based on your environment
spring.datasource.hikari.data-source-properties.connectTimeout=10

# pgJDBC 9.4.1200+, slightly more than connectTimeout
spring.datasource.hikari.data-source-properties.hostRecheckSeconds=11

# any pgJDBC version, an example for (3 hosts) * (connectTimeout + 1s margin), or 0 to wait indefinitely
spring.datasource.hikari.data-source-properties.loginTimeout=33

# pgJDBC 9.4.1200+, if all hosts are equivalent and connection order doesn't matter
spring.datasource.hikari.data-source-properties.loadBalanceHosts=true

# pgJDBC 9.4.1209+, "on conflict" fixed in pgJDBC 42.2.2+,
# only if PreparedStatement.executeBatch return result isn't important
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

# any HikariCP, can also be specified via spring.datasource.name=poolName
spring.datasource.hikari.pool-name=poolName

# HikariCP 1.3.0+, if you need jmx metrics
spring.datasource.hikari.register-mbeans=true
